logging.level:
  org.springframework.jdbc: debug
  itemservice.db.repository.mybatis: trace

spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa

#MyBatis
mybatis:
  type-aliases-package: itemservice.db.domain
  configuration:
    map-underscore-to-camel-case: true
